//
//  MovieListWorker.swift
//  AwesomeMovies
//
//  Created by Mustafa Saify on 02/02/19.
//  Copyright (c) 2019 Mustafa Saify. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private let baseURL = URL(string: Bundle.main.apiBaseUrl())!
private let apiKey = Bundle.main.apiKey()

class MovieListWorker {
    
    private let dataManager = MovieListDataManager(dataSource: MovieListServiceDatasource(baseURL: baseURL,
                                                                        apiKey: apiKey,
                                                                        cacheTime: oneHour))
    
    func fetchMovies(for filter: MovieFilterDetails, page: Int?, completion: @escaping (FeedResult<[Movie]>) -> Void) {
        dataManager.fetchMovies(for: filter, page: page, completion: completion)
    }
}
