//
//  MovieListModels.swift
//  AwesomeMovies
//
//  Created by Mustafa Saify on 02/02/19.
//  Copyright (c) 2019 Mustafa Saify. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieList {
  // MARK: Use cases
    
    enum FetchMovies {
        
        struct Response {
            var movies: [Movie]?
            var append: Bool
            var imageAccess: ImageAccess?
            var error: Error?
        }
        
        struct ViewModel {
            var movies: [MovieViewModel]?
            var append: Bool
            var error: String?
        }
    }
    
    enum Footer {
        
        struct Response {
            var state: LoadingItemState<[Movie]>
        }
        
        struct ViewModel {
            var footerViewModel: MovieListFooterViewModel
        }
    }
}
