//
//  MovieListRouter.swift
//  AwesomeMovies
//
//  Created by Mustafa Saify on 02/02/19.
//  Copyright (c) 2019 Mustafa Saify. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListRouterInput {
    //func navigateToMovieDetails()
}

enum MovieListSegue: String {
    case movieDetails = "ShowMovieDetailsScene"
    case filter = "ShowMovieFilterScene"
}

class MovieListRouter: MovieListRouterInput {
    
    weak var viewController: MovieListViewController!
  
    func passDataToNextScene(_ segue: UIStoryboardSegue) {
        
        if segue.identifier == MovieListSegue.movieDetails.rawValue {
            passDataToMovieDetailsScene(segue)
        }
        else if segue.identifier == MovieListSegue.filter.rawValue {
            passDataToMovieFilterScene(segue)
        }
    }
    
    func passDataToMovieDetailsScene(_ segue: UIStoryboardSegue) {
        
        guard let selectedIndexPath = viewController.tableView.indexPathForSelectedRow else { return }
        let selectedMovie = viewController.output.movies[selectedIndexPath.row]
        let movieDetailsViewController = segue.destination as! MovieDetailsViewController
        movieDetailsViewController.output.movie = selectedMovie
    }
    
    func passDataToMovieFilterScene(_ segue: UIStoryboardSegue) {
        
        let filterViewController = (segue.destination as! UINavigationController).viewControllers.first as! MovieFilterViewController
        filterViewController.output.filterDetails = viewController.output.filterDetails
    }
}
